### ISSUE TITLE
Hardcoded path in public/js/module.js problematic if path does not start with icingaweb2/

### ISSUE THREAD

**Issue by jayjensen** [sol1/icinga-clustergraph#2]
If the path

`https://<domain>/<path> `

does not start with icingaweb2/ , the module is not 
able to fetch the data for the graphing.
The path "/icingaweb2/  is hardcoded in the public/js/module.js :

`fetch("/icingaweb2/clustergraph/index/data")`

It would be nice, if the leading path could be configurable, for example a "/" , if icingaweb2 runs
directly under the webroot (domain).

Greetings.
Jay

**Comment by davekempe** [comment]
I thought I fixed it in 1.0.3 but its broken and I'm not sure why yet. I am only spending minutes at a time on this, so I will have another crack once I have more time.

**Comment by sol1-matt** [comment]
I'm not sure if you had a 1.0.3 and deleted it or you mean 1.0.2 @davekempe.  But there is now a new v1.0.3 release that uses a module relative path for the api call, it has reverted the changes in 1.0.2 originally added to fix this issue.

@jayjensen give this version a go and let us know if it solve the problem for were having.

**Comment by sol1-matt** [comment]
fixed in b4f9bbf575f6038ddf1421b3d6d52bc792d92ffa

**Comment by sol1-matt** [comment]
deleted release and recreated with updated version info for the module

**Comment by jayjensen** [comment]
> @jayjensen give this version a go and let us know if it solve the problem for were having.

Works great, thank you.

Greetings,
Jay
