### ISSUE TITLE
Zone names barely visible with light mode

### ISSUE THREAD

**Issue by log1-c** [sol1/icinga-clustergraph#4]
First of all, cool module! Thanks!

For light mode users the zones names are hardly visible:
![image](https://github.com/sol1/icinga-clustergraph/assets/24474580/6c850081-6fcf-403a-8f1e-b196fc6ac901)

Cheers :)

**Comment by sol1-matt** [comment]
I had a look at this and it's being troublesome.

All the font and line colours are hard coded in the module, the background-color is part of the Icinga theme.

The icinga theme uses a root css var `--text-color` which changes based on the theme selected and we should be able to use it to solve the problem. But setting it on the svg fill property fails to change the zone text colour, the fill value is set correctly but it doesn't change anything. 

If I try and read the computedStyles in js I can't see the `--text-color` property.

~~I can see the `color` property but it's value when read by cluster graph isn't the same as the `--text-color` value for the given theme. If I read the color property in the  console I get the correct value.~~

We can find the right theme color by reading the menu color, specifically `#navigation`'s `color` property.

**Comment by sol1-matt** [comment]
@log1-c new release https://github.com/sol1/icinga-clustergraph/releases/tag/v1.0.5 that should fix the problem for you.

**Comment by log1-c** [comment]
works. thanks for the quick fix!
