### ISSUE TITLE
upper section of graph is truncated/cut off

### ISSUE THREAD

**Issue by tectumopticum** [sol1/icinga-clustergraph#5]
First of all thanks for this nice module!
When I click on "ClusterGraph" in the left side-menu of icingaweb2 I see this:
![image](https://github.com/sol1/icinga-clustergraph/assets/66269591/253ae291-e025-4efa-820f-5b3d63287509)

The first upper leaf seems to be truncated. I've tested this with "Edge" (Version 118.0.2088.76 (Official Build) (64-Bit)) and Firefox 115.4.0esr (64-Bit). A colleague gets the same results. It makes no difference, if we change from dark- to light or system-theme.
We have the "Company theme"-module enabled.

Icinga Web 2 Version | 2.12.0
PHP Version | 8.0.30
Loaded Libraries
icinga/icinga-php-thirdparty | 0.12.0
icinga/icinga-php-library | 0.13.0

**Comment by sol1-matt** [comment]
Can reproduce this problem by having a small number of zones and endpoints
Problem related to the svg viewbox and height

**Comment by sol1-matt** [comment]
@tectumopticum new release with a fix for your problem is available [v1.0.6](https://github.com/sol1/icinga-clustergraph/releases/tag/v1.0.6), I've tested it on a couple of different clusters and it aligns better vertically.

Could you try this and let me know if it works on your cluster.

**Comment by tectumopticum** [comment]
> @tectumopticum new release with a fix for your problem is available [v1.0.6](https://github.com/sol1/icinga-clustergraph/releases/tag/v1.0.6), I've tested it on a couple of different clusters and it aligns better vertically.
> 
> Could you try this and let me know if it works on your cluster.

Just tested your fix - works and aligns perfect now! Thanks a lot for your efforts.

**Comment by tectumopticum** [comment]
tested v1.0.6 - works fine now
