### ISSUE TITLE
Switching from v1.03 to v1.0.5 breaks fetching of data

### ISSUE THREAD

**Issue by jayjensen** [sol1/icinga-clustergraph#6]
Hi.

## Description

After switching from version v1.0.3 to version v1.0.5, data from 
<domain>/clustergraph/index/data 
can't be fetched anymore.

The graph isn't displayed anymore.

## Error

The raw error when calling the endpoint is:

`Fatal error: Uncaught ErrorException: Uncaught Zend_Controller_Response_Exception: Invalid HTTP response code in /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Response/Abstract.php:288 Stack trace: #0 /usr/share/icingaweb2/application/controllers/ErrorController.php(80): Zend_Controller_Response_Abstract->setHttpResponseCode() #1 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(516): Icinga\Controllers\ErrorController->errorAction() #2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch() #3 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch() #4 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch() #5 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch() #6 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...') #7 {main} Next Zend_Controller_E in /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Plugin/Broker.php on line 262`

## Versions

icingaweb2:              2.12.0
icinga-php-library:    0.13.0

Thanks and greetings,
Jay

**Comment by sol1-matt** [comment]
This is a php error, changes between 1.0.3 and 1.0.5 that would affect this are
- Change to the default permissions `permissions = [ "objects/query/Zone", "objects/query/Endpoint", "objects/query/Host" ]`
- Renamed the class that returns icinga data
- Adding additional data to endpoints so we know the state of hosts that match the endpoint name `$endpointData['state'] = $host['attrs']['state'];`

@jayjensen could you check your permissions are correct, normally found in `/etc/icinga2/conf.d/api-users.conf`. With the 1.0.5 version we introduced a new api call that requires additional permissions for the api user to function.

**Comment by jayjensen** [comment]
@sol1-matt 

"objects/query/Host" was missing at the API permission list.
Honestly, this wasn't required before and I didn't look for the new description in the "Configuration" tab, my mistake, sorry.

Thank you very much. 
v1.0.5 works fine now.

Greetings,
Jay
